name: Deploy to SFTP

on:
  push:
    branches:
      - main # Cambia esto a la rama que uses para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y ssh

      - name: Upload files via SFTP
        uses: webactions/sftp-deploy@v1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          #local-path: ./path/to/your/files/* # Cambia esto a la ruta de los archivos que quieras enviar
          remote-path: /xxx/ # Cambia esto a la ruta en el servidor SFTP          

