

name: Deploy to SFTP

on:
  push:
    branches:
      - master  # Cambia esto a la rama que usas para deploys.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          #password: ${{ secrets.FTP_PASSWORD }}
          password: "123456"
          protocol: ftps # Asegúrate de especificar sftp          
          port: 22          
          server-dir: public_html/xxx/ # Cambia esto a la ruta en el servidor SFTP
          timeout: 100000
          