

name: Deploy to SFTP

on:
  push:
    branches:
      - master  # Cambia esto a la rama que usas para deploys.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local-dir: ./* # Cambia esto a la ruta de los archivos que quieres enviar
          server-dir: /xxx/ # Cambia esto a la ruta en el servidor SFTP
          protocol: ftps # Asegúrate de especificar sftp          